### PR TITLE
Add `Ag3.12` and `Ag3.13` VUG

### PR DESCRIPTION
**Pull request by jonbrenas**
I don't remember how not to have the 'Note: you may need to restart the kernel to use updated packages.` message.

I also modified Ag3.11 because of the links was incorrectly pointing to 3.10.

### CODE REVIEW

**Review by ahernank — COMMENTED** [review]
Thanks @jonbrenas -- VUGs look great. Just a small note that you might also want to update the `_toc.yml` as part of this PR, to ensure these release appear on the book. You can see an example on the PR for [Ag3.11 ](https://github.com/malariagen/vector-data/pull/81).

**Comment by jonbrenas** [comment]
Thanks @ahernank, that's done.

**Review by ahernank — APPROVED** [review]
Thanks @jonbrenas!

**Comment by ahernank** [comment]
I will merge this one now, unless any concerns. :)

**Pull request merged**
